In [1]:
# Import packages 
import numpy as np 

In [2]:
# Open data, convert every digit to integer, and split the data. 
pixels = [int(x) for x in open('d8p1input').read().split()]
pixels = [x for x in str(pixels)][1:15001]

In [3]:
# Define pixel shape and convert list to array 
shape = (6, 25)
pArray = np.array(pixels)

In [4]:
# Initiate an empty list to store each image 
ls = []

# Creates a range from 0 to 15000 each 150. This will separate the pixels array to separate each image 
rng = np.arange(0, 15000, 150)

# Iterate over the array, separate, and store as a separate list 
for i in rng:
    p = pArray[i:i+150]
    l = p.reshape(shape)
    ls.append(l)

In [5]:
# Initiate an empty list to store the results of each image 
results = []

# Iterate over each image in ls
for x in ls: 
    # Counters for 0s, 1s, and 2s.
    zeros, ones, twos = 0, 0, 0
    flatList = [i for j in x for i in j]
    for y in flatList: 
        if y == '0': 
            zeros += 1
        elif y == '1': 
            ones += 1
        else: 
            twos += 1
    results.append([zeros, ones, twos])

In [6]:
# Get sublist with lowest number of zeros. Then multiply number of 1s and 2s
minZero = min(x[0:] for x in results)
minZero[1] * minZero[2]

2080

In [7]:
## Part two 
# Initiate an array that will serve as the surface on which to scan all images 
surface = np.array([2] * 150)

In [8]:
# Iterate over each image. 
for i in ls: 
    # Flatten the list of list for better iteration
    flatList = [int(x) for j in i for x in j]
    # If the element within the list is 0, then it is "colored in". 0s outrank 2s, 1s outrank 0s.  
    for y in range(len(flatList)): 
        if flatList[y] == 0 and surface[y] == 2:
            surface[y] = 0
        elif flatList[y] == 0 and surface[y] == 1:
            surface[y] = 1
        elif flatList[y] == 1 and surface[y] == 2:
            surface[y] = 1
        elif flatList[y] == 2 and surface[y] == 2:
            surface[y] = 2

In [9]:
# Reshape the newly colored surface in a 6 x 25 matrix 
final = surface.reshape(shape)

# Print the surface. 
for i in final:
    print(i)

[0 1 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 0 0 1 0 0 0 1]
[1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1]
[1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0]
[1 1 1 1 0 1 0 0 1 0 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0]
[1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0]
[1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0]
